apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: cs3219
spec:
  selector:
    app: customer-service
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      # nodePort: 31307
  type: ClusterIP # NodePort